# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pylint + Pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
        # run pylint
        pylint --fail-under=8 $(git ls-files '*.py' | grep -v 'tests')
    - name: Test with pytest
      env:
        CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        YOUTUBE_JSON: ${{ secrets.YOUTUBE_JSON }}
      run: |
        # Write github secret to a file: app .config.json & youtube .oauth.json
        echo $env:CONFIG_JSON >> $GITHUB_WORKSPACE/.config.json
        echo $env:YOUTUBE_JSON >> $GITHUB_WORKSPACE/.oauth.json
        
        echo $GITHUB_WORKSPACE/.config.json

        cat $GITHUB_WORKSPACE/.config.json

        pytest
